services:
  - type: cron
    name: credmapper
    plan: standard
    env: node
    region: oregon
    rootDir: ./
    branch: main
    schedule: '0 0 * * *'
    buildCommand: pnpm i && pnpm -F db migrate:prod
    startCommand: pnpm -F indexer sync
    buildFilter:
      paths:
        - packages/indexer/**
        - packages/db/**
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: credmapper-db
          property: connectionString
      - fromGroup: credmapper
      - key: NODE_VERSION
        value: 18.14.0

databases:
  - name: credmapper-db
    databaseName: credmapper
    region: oregon
    plan: pro
    postgresMajorVersion: 15
