services:
  - type: cron
    name: warmup-cred-api
    runtime: node
    branch: main
    region: oregon
    rootDir: ./
    schedule: '* * * * *'
    startCommand: sh ./packages/cred-api/scripts/warmup.sh
    buildFilter:
      paths:
        - packages/cred-api/scripts/**
      ignoredPaths:
        - packages/coindata/**
        - packages/cred-api/**
        - packages/indexer/**
  - type: cron
    name: credmapper
    plan: pro plus
    env: node
    region: oregon
    rootDir: ./
    branch: main
    schedule: '0 0 * * *'
    buildCommand: pnpm i && pnpm -F db migrate:prod
    startCommand: pnpm -F indexer indexOneOff
    buildFilter:
      paths:
        - packages/indexer/**
        - packages/db/**
      ignoredPaths:
        - packages/cred-api/**
        - packages/coindata/**
        - packages/app/**
    envVars:
      - fromGroup: credmapper
      - key: NODE_VERSION
        value: 18.14.0
  - type: cron
    name: credmapper-2
    plan: standard
    env: node
    region: oregon
    rootDir: ./
    branch: main
    schedule: '0 0 * * *'
    buildCommand: pnpm i && pnpm -F db migrate:prod
    startCommand: pnpm -F indexer exec ts-node ./src/indexCred.ts
    buildFilter:
      paths:
        - packages/indexer/**
        - packages/db/**
      ignoredPaths:
        - packages/cred-api/**
        - packages/coindata/**
        - packages/app/**
    envVars:
      - fromGroup: credmapper
      - key: NODE_VERSION
        value: 18.14.0

databases:
  - name: credmapper-db
    databaseName: credmapper
    region: oregon
    plan: pro plus
    postgresMajorVersion: 15
