[package]
name = "circuits"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-ec = "0.4.2"
ark-ff = "0.4.2"
ark-secp256k1 = "0.4.0"
ark-secq256k1 = "0.4.0"
ark-serialize = "0.4.2"
num-bigint = "0.4.4"
sapir = { git = "https://github.com/personaelabs/sapir.git", features = [
    "profiler",
], branch = "main" }
wasm-bindgen = "0.2.87"

[dev-dependencies]
ethers = "2.0.10"
ark-std = "0.4.0"

[profile.release]
lto = true
opt-level = 3
